### ISSUE TITLE
Android IllegalStateException on ZDPortalHome.show()

### ISSUE THREAD

**Issue by Ferossgp** [zoho/react-native-zohodesk-portal-sdk#15]
Android app crashes on Android when calling `ZDPortalHome.show()` with the following exception:

```sh
java.lang.RuntimeException: Unable to start activity ComponentInfo{REDACTED/com.zoho.desk.asap.common.activities.ZDPBaseActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

FATAL EXCEPTION: main
Process: REDACTED, PID: 31418
java.lang.RuntimeException: Unable to start activity ComponentInfo{REDACTED/com.zoho.desk.asap.common.activities.ZDPBaseActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4169)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:852)
	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:815)
	at androidx.appcompat.app.AppCompatDelegateImpl.initWindowDecorActionBar(AppCompatDelegateImpl.java:556)
	at androidx.appcompat.app.AppCompatDelegateImpl.getSupportActionBar(AppCompatDelegateImpl.java:543)
	at androidx.appcompat.app.AppCompatActivity.getSupportActionBar(AppCompatActivity.java:163)
	at com.zoho.desk.asap.common.activities.ZDPBaseActivity.onCreate(ZDPBaseActivity.kt:23)
	at android.app.Activity.performCreate(Activity.java:8591)
	at android.app.Activity.performCreate(Activity.java:8570)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
	... 12 more
```

App theme is defined as follows `<style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">`

The theme is changed after the [Splashscreen to the one above](https://github.com/zoontek/react-native-bootsplash#android-1)

**Comment by Ferossgp** [comment]
Fixed by adding new activity in AppManifest.xml

```
      <activity
        android:name="com.zoho.desk.asap.common.activities.ZDPBaseActivity"
        android:theme="@style/AppTheme" <---- App style that extends on Theme.AppCompat
      />
```
